services:
  ecommerce.httpapi:
    image: ecommerce.httpapi
    build:
      context: .
      dockerfile: src/Ecommerce.HttpApi/Dockerfile
    depends_on:
      - products_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  products_db:
    image: postgres:latest
    container_name: ecommerce_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Testpass123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
